- name: print the course information again
  hosts: web
  become: yes
  vars: # variables from play level
    COURSE: "Devops with Aws"
    DURATION: "120hrs"
    TRAINER: "shivakumar reddy"
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi iam learning {{ COURSE }}, with duration {{ DURATION }}, by the trainer {{ TRAINER }}"

  - name: print the course information again
    vars: # variables from task level 
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi iam learning {{ COURSE }}, with duration {{ DURATION }}, by the trainer {{ TRAINER }}"

# play level variables can be overidden by the task level variabels
  