- name: variables from files
  hosts: web
  vars_file:
    - vars.yaml
  tasks:
  - name: print the varaibles from files
    ansible.builtin.debug:
      msg: "Hi iam learning {{ COURSE }}, with the duration {{ DURATION }}, by the trainer {{ TARINER }}