- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false
  - name: DURAUION
    prompt: please enter the duration
    private: false
  - name: TRAINER
    prompt: please enter the trainer name
    private: false
  tasks:
  - name: print the course information by prompt
    ansible.builtin.debug:
      msg: "Hi iam learing {{ COURSE }}, with duration {{ DUARTION }} by the trainer {{ TRAINER }}"
