- name: loops general example
  hosts: web
  tasks:
  - name: print the names
    ansible.builtin.debug:
      msg: "hello please print the name {{ item }}"
    loop:
    - meerjan
    - jareena
    - chashan
    - kashira