- name: install or remove packages using loops
  hosts: web
  become: yes
  tasks:
  - name: install or remove packages using loops
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'mysql',state: 'present'}
    - {name: 'nginx',state: 'present'}
    - {name: 'postfix',state: 'present'}
    - {name: 'httpd',state: 'present'}
    - {name: 'nodejs',state: 'present'}