- name: demo on filters or functions
  hosts: local
  connection: local
  tasks:
  - name: convert the string to upper case
    vars:
      greeting: "hello ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"