- name: create user if not exist based on condition
  hosts: local
  connection: local
  tasks:
  - name: check weather the user is exist
    ansible.builtin.command: id user
    rigister: USER
    ignore_errors: true