- name: create user if not exist based on condition
  hosts: local
  connection: local
  tasks:
  - name: check weather the user is exist
    ansible.builtin.command: id user
    register: USER
    ignore_errors: true

  - name: print thr user info
    ansible.builtin.debug:
      msg: "user info is : {{ USER }}"

  - name: create user if not exist
    ansible.builtin.command: useradd expense
    when : rc != 0