- name: create ec2 instancer and r53 records
  hosts: local
  connection: local
  vars:
    vpc_subnet_id: vpc-053fda7bc9606768e
    instance_type: t3.micro
    security_group: sg-0d0488aad8797fa18
    image_id: ami-09c813fb71547fc4f
    zone: meerjan.online
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ security_group }}"
      image_id: "{{ image_id }}"
    loop:
    - mysql
    - backend
    - frontend
    register: ec2-instances