- name: create ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
    vpc_subent_id: subnet-0d379f052e48ae9e0
    security_id: sg-0d0488aad8797fa18
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    zone: meerjan.online
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      security_id: "{{ security_id }}"
      ami_id: "{{ ami_id }}"
      register: "ec2_instances"
    loop:
    - mysql
    - backend
    - frontend