- name: install and run and enable nginx
  hosts: nginx
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present
      
  - name: run and enable nginx 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes